---
  - hosts: ec2
    become: yes
    vars:
      MySQL_root_pass: root
    tasks:
     - name: set mysql root password before install
       debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
       debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
     - name: Install Mysql
       apt: name= {{item}} state=present update_cache=yes
       with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb

